'use client';
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js';
import { configureBoneyard } from 'boneyard-js/react';

import _notifications from './notifications.bones.json';

configureBoneyard({
  darkColor: '#1a1a2e',
  animate: 'shimmer',
  darkShimmerColor: '#2d2d50',
  speed: '1.5s',
  shimmerAngle: 110,
  stagger: 80,
  transition: 300,
});

registerBones({
  notifications: _notifications,
});
